export const SUBSCRIPTION_PLANS_STORAGE_KEY = "ecoequity_subscription_plans";

export const initialSubscriptionPlans = [
  {
    id: "PLAN-BASIC",
    name: "Basic",
    description: "For casual gardeners and beginners.",
    priceMonthly: "Free",
    priceYearly: "Free",
    billingNoteMonthly: "Forever",
    billingNoteYearly: "Forever",
    color: "#16a34a",
    accentColor: "#16a34a",
    bg: "#ffffff",
    badge: "",
    ctaLabel: "Current Plan",
    billingType: "free",
    clientVisible: true,
    users: "850",
    revenue: "₱0",
    features: ["General AI Chat", "Community Access"],
    excludedFeatures: ["24/7 Plant Doctor", "Photo Diagnostics", "Priority Support"],
  },
  {
    id: "PLAN-PRO",
    name: "Pro",
    description: "For serious growers & urban farmers.",
    priceMonthly: "₱499",
    priceYearly: "₱4,790",
    billingNoteMonthly: "per month",
    billingNoteYearly: "per year, billed annually",
    color: "#ca8a04",
    accentColor: "#eab308",
    bg: "linear-gradient(145deg, rgba(234,179,8,0.05), rgba(255,255,255,1))",
    badge: "Most Popular",
    ctaLabel: "Subscribe Now",
    billingType: "paid",
    clientVisible: true,
    users: "345",
    revenue: "₱172K",
    features: ["Unlimited AI Chat", "24/7 AI Plant Doctor", "Advanced Photo Diagnostics", "Priority Support"],
    excludedFeatures: ["API Access"],
  },
  {
    id: "PLAN-ENTERPRISE",
    name: "Enterprise",
    description: "For commercial farms & businesses.",
    priceMonthly: "₱1,499",
    priceYearly: "₱14,390",
    billingNoteMonthly: "per month",
    billingNoteYearly: "per year, billed annually",
    color: "#0284c7",
    accentColor: "#0ea5e9",
    bg: "rgba(14, 165, 233, 0.02)",
    badge: "",
    ctaLabel: "Contact Sales",
    billingType: "contact",
    clientVisible: true,
    users: "50",
    revenue: "₱450K",
    features: ["Everything in Pro", "Dedicated Human Agent", "24/7 VIP Phone Support", "Custom API Access", "Team Analytics Dashboard"],
    excludedFeatures: [],
  },
];
